package com.myroslav.derevyanko.exchangerate.GUI;

import com.myroslav.derevyanko.exchangerate.PrivatbankAnswer.PrivatAnswer;
import com.myroslav.derevyanko.exchangerate.PrivatbankAnswer.Converter;
import com.myroslav.derevyanko.exchangerate.PrivatbankAnswer.CourseRequest;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;

/**
 *
 * @author Myroslav_D
 */
public class MainFrame extends javax.swing.JFrame
{

    private List<JLabel> cashExchangeRate = new ArrayList<>();
    private List<JLabel> cashlessExchangeRate = new ArrayList<>();
    private List<PrivatAnswer> cashExchangeRateAnsw;
    private List<PrivatAnswer> cashlessExchangeRateAnsw;
    private String cashlessExchangeRateURL = "https://api.privatbank.ua/p24api/pubinfo?exchange&json&coursid=11";
    private String cashExchangeRateURL = "https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5";

    public MainFrame() throws IOException
    {
        initComponents();
        setVisible(true);
        setCourse();
        URL url = new URL("http://credit.poltava.ua/wp-content/uploads/2016/06/converter.png");
        Image image = ImageIO.read(url);
        setIconImage(image);
        jButton2ActionPerformed(new ActionEvent(new Object(), 1, "do"));

    }

    public void setCourse() throws IOException
    {
        cashExchangeRate.add(jLabelСashUSD);
        cashExchangeRate.add(jLabelCashEUR);
        cashExchangeRate.add(jLabelCashRUR);
        cashExchangeRate.add(jLabelCashBTC);

        cashlessExchangeRate.add(jLabelCashlessUSD);
        cashlessExchangeRate.add(jLabelCashlessEUR);
        cashlessExchangeRate.add(jLabelCashlessRUR);
        cashlessExchangeRate.add(jLabelCashlessBTC);

        CourseRequest request = new CourseRequest();
        cashExchangeRateAnsw = request.getExchangeRate(cashExchangeRateURL);
        cashlessExchangeRateAnsw = request.getExchangeRate(cashlessExchangeRateURL);

        for (int i = 0; i < 4; i++)
        {
            cashExchangeRate.get(i).setText(cashExchangeRateAnsw.get(i).getCcy() + " = " + cashExchangeRateAnsw.get(i).getBuy() + "/" + cashExchangeRateAnsw.get(i).getSale());
            cashlessExchangeRate.get(i).setText(cashlessExchangeRateAnsw.get(i).getCcy() + " = " + cashlessExchangeRateAnsw.get(i).getBuy() + "/" + cashlessExchangeRateAnsw.get(i).getSale());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelСashUSD = new javax.swing.JLabel();
        jLabelCashEUR = new javax.swing.JLabel();
        jLabelCashRUR = new javax.swing.JLabel();
        jLabelCashBTC = new javax.swing.JLabel();
        jLabelCashlessUSD = new javax.swing.JLabel();
        jLabelCashlessEUR = new javax.swing.JLabel();
        jLabelCashlessRUR = new javax.swing.JLabel();
        jLabelCashlessBTC = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Курс валют");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(960, 288));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Курс валют Приват банку");

        jLabel2.setText("Готівковий курс");

        jLabel3.setText("Безготівковий курс");

        jLabelСashUSD.setText("jLabel4");

        jLabelCashEUR.setText("jLabel5");

        jLabelCashRUR.setText("jLabel6");

        jLabelCashBTC.setText("jLabel7");

        jLabelCashlessUSD.setText("jLabel8");

        jLabelCashlessEUR.setText("jLabel9");

        jLabelCashlessRUR.setText("jLabel10");

        jLabelCashlessBTC.setText("jLabel11");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ковнвертер валют");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Для готівкових розрахунків", "Для безготівкових розрахунків" }));
        jComboBox1.setSelectedIndex(1);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Купівля", "Продаж" }));
        jComboBox3.setSelectedIndex(1);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "RUR", "UAH" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "RUR", "UAH" }));
        jComboBox5.setSelectedIndex(3);

        jTextField1.setText("1000");

        jLabel14.setText("jLabel14");

        jButton1.setText("Оновити курс");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Розрахувати");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("* курс BTC в USD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelСashUSD)
                                    .addComponent(jLabelCashlessUSD))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelCashlessEUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCashEUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelCashRUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCashlessRUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCashlessBTC)
                                    .addComponent(jLabelCashBTC)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addGap(0, 397, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelСashUSD)
                    .addComponent(jLabelCashEUR)
                    .addComponent(jLabelCashRUR)
                    .addComponent(jLabelCashBTC))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelCashlessUSD)
                    .addComponent(jLabelCashlessEUR)
                    .addComponent(jLabelCashlessRUR)
                    .addComponent(jLabelCashlessBTC))
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jButton2))
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        getAccessibleContext().setAccessibleDescription("Курс валют");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            setCourse();
        }
        catch (IOException ex)
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String selectedExchangeCourse = jComboBox1.getSelectedItem().toString();
        String selectedExchangeCourseType = jComboBox3.getSelectedItem().toString();
        String initialCurrency = jComboBox4.getSelectedItem().toString();
        String finalCurrency = jComboBox5.getSelectedItem().toString();
        double value = Double.valueOf(jTextField1.getText());

        switch (selectedExchangeCourse)
        {
            case "Для безготівкових розрахунків":
                switch (selectedExchangeCourseType)
                {
                    case "Купівля":
                    {
                        jLabel14.setText("" + Converter.convertBuy(cashlessExchangeRateAnsw, value, initialCurrency, finalCurrency));
                        break;
                    }
                    case "Продаж":
                    {
                        jLabel14.setText("" + Converter.convertSell(cashlessExchangeRateAnsw, value, initialCurrency, finalCurrency));
                        break;
                    }

                }
                break;
            case "Для готівкових розрахунків":
                switch (selectedExchangeCourseType)
                {
                    case "Купівля":
                    {
                        jLabel14.setText("" + Converter.convertBuy(cashExchangeRateAnsw, value, initialCurrency, finalCurrency));
                        break;
                    }
                    case "Продаж":
                    {
                        jLabel14.setText("" + Converter.convertSell(cashExchangeRateAnsw, value, initialCurrency, finalCurrency));
                        break;
                    }
                }
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCashBTC;
    private javax.swing.JLabel jLabelCashEUR;
    private javax.swing.JLabel jLabelCashRUR;
    private javax.swing.JLabel jLabelCashlessBTC;
    private javax.swing.JLabel jLabelCashlessEUR;
    private javax.swing.JLabel jLabelCashlessRUR;
    private javax.swing.JLabel jLabelCashlessUSD;
    private javax.swing.JLabel jLabelСashUSD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
